"""add notifications table

Revision ID: 651a9a684242
Revises: 550d2b1c5884
Create Date: 2026-02-10 21:17:59.362104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651a9a684242'
down_revision = '550d2b1c5884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('WATERING_DUE', 'WATERING_OVERDUE', 'FERTILIZATION_DUE', 'FERTILIZATION_OVERDUE', 'TREATMENT_REMINDER', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('plant_name', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
