"""Add watering and fertilization tables

Revision ID: 936fc3f1c9cb
Revises: 73a92cc837f6
Create Date: 2026-02-09 20:40:05.304653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936fc3f1c9cb'
down_revision = '73a92cc837f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilization_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('fertilizer_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilization_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('fertilization_schedule_id', sa.UUID(), nullable=True),
    sa.Column('fertilized_at', sa.DateTime(), nullable=False),
    sa.Column('fertilizer_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fertilization_schedule_id'], ['fertilization_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('watering_schedule_id', sa.UUID(), nullable=True),
    sa.Column('watered_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watering_schedule_id'], ['watering_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_logs')
    op.drop_table('fertilization_logs')
    op.drop_table('watering_schedules')
    op.drop_table('fertilization_schedules')
    # ### end Alembic commands ###
